### ISSUE TITLE
Rebase to the latest WME

### ISSUE THREAD

**Issue by berestovskyy** [WMEValidator/validator#1]

**Comment by berestovskyy** [comment]
I am not quite sure if you see this guys, but all the UI styles are broken for me, i.e. checkboxes are over the text, labels and inputs are shifted etc.

**Comment by justins83** [comment]
Everything displays properly for me
![](https://i.imgur.com/IHYlfMh.png)
![](https://i.imgur.com/zB5BLRM.png)

**Comment by berestovskyy** [comment]
Hm... Could you please try it with all other script disabled?

**Comment by berestovskyy** [comment]
It seems the cause was `W.location`. No more issues with the styles, closing...
