### ISSUE TITLE
Add support for speed limits

### ISSUE THREAD

**Issue by berestovskyy** [WMEValidator/validator#14]
Quote:
  I'd like to be able to check for incorrect speed limits, i.e. any that
  don't end in 0 (for my country). It will be necessary to have ${speed-kmh}
  and ${speed-mph}, so that checks can be done against the appropriate units.
  I know I've accidentally input some speeds with the wrong units, so that
  would be a good check to add to a localisation pack.

  Note to developer: fwd/revMaxSpeedUnverified == true should count as a
  missing speed limit, even if fwd/revMaxSpeed is set. Editors will need to
  verify these.
  Also, watch out for 1 way segments that only need 1 speed setting.

**Comment by davidakachaos** [comment]
I would like to add that the checks for unneeded nodes currently breaks because of missing speedlimit support. Some segments are cut in two because of different speed limits on them, currently Validator reports those cases as unneeded nodes.

**Comment by berestovskyy** [comment]
I guess this one is pretty much done.
