### ISSUE TITLE
Show report not working in Firefox

### ISSUE THREAD

**Issue by davidakachaos** [WMEValidator/validator#48]
As skubko commented on the forum:

> Thanks, but "Show report" was not fixed for me :disappointed: ... Trying on Firefox, opens new tab and that one immediately closes...

[forum reply](https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=1867253#p1867162)

**Comment by berestovskyy** [comment]
Confirmed on the latest Firefox. While other windows open ok (list of available checks for example), show report indeed opens and then immediately closes :(

**Comment by davidakachaos** [comment]
Strange thing is, I didn't touch the "Show Report" part of the code I think? I fixed the "Show list of available checks" thing in Chrome. Show Report worked in Chrome? Anyway, something to look into tomorrow.

**Comment by justins83** [comment]
This isn't a new problem - people have been complaining about this since Validator was re-released.  You didn't break it :)

**Comment by berestovskyy** [comment]
Prior the release I checked both "show report" and "list of checks". Both worked fine in Chrome.

Just like Justin said, it's not your fault, it's just either a bug in Validator or just a new version of Firefox...

**Comment by davidakachaos** [comment]
O I'm fully capable of breaking something without touching it :rofl: 
Nah, I'll look into it tomorrow, or one of you can fix it? I mean, if my approach with the available checks works in Firefox, maybe a quick fix is there for the "Show Report"?

**Comment by berestovskyy** [comment]
Have a look, David. Get familiar with the code...

**Comment by berestovskyy** [comment]
It's not that urgent though... :turtle: :relaxed:
