### ISSUE TITLE
[Idea] Validate places?

### ISSUE THREAD

**Issue by davidakachaos** [WMEValidator/validator#57]
So I'm thinking, it's WME Validator right? Not WME Segment Validator 😉 
So should we add places to things we can check? I think they could be validated in similar ways as segments are being checked right now. There could be rules like "Place has no name" or "This place category isn't used in this country! Refer to the wiki for solutions."
These checks would possibly add at lot more load to the checks, I think? Or would it be manageable?
I think it would help editors out when add/updating places in Waze to be notified if they do something wrong, like we do now with segments.
Of course we can gate the "places validation" with a checkbox setting, defaulting to off at first. Like we can enable slow checks now if we want.

So that my idea. Love it? Hate it? Let me know.

**Comment by berestovskyy** [comment]
We definitely need support for places. But it a bit different way, please have a look at #58 for my long-term vision.

Basically, Validator must iterate over all the places as you suggest, but IMO validations must be implemented outside the script. Or even some existing scripts must be reused, sure slightly modified to operate as a plugin.

**Comment by davidakachaos** [comment]
We'll discuss this further in that issue and put this one on hold for now? (pending a plugin system?)

**Comment by berestovskyy** [comment]
IMO we can implement some basic support for Places now. This will allow us to get familiar with the Places API etc.

We just need to keep in mind our long-term vision and do not invest much time in checks itself, but rather in the "infrastructure" around those checks.
