### ISSUE TITLE
Add more exceptions for speed limit checks

### ISSUE THREAD

**Issue by berestovskyy** [WMEValidator/validator#60]
Speed limit checks should NOT be applied to:

1. Roundabouts.

2. At-grade connectors (ACGs), i.e. short segments.

The minimum length of the segment to exclude from speed limit checks should be estimated by scanning a big area with lots of connectors.

**Comment by davidakachaos** [comment]
Couldn't we just define short segments as being shorter than 5 meters?

**Comment by berestovskyy** [comment]
IMO on some large intersections those connecters might be up to few tens of meters... Not sure about the exact length though. 30-50 m?

**Comment by davidakachaos** [comment]
Disclaimer; I edit in the Netherlands mostly and we don't have such huge intersections here (I think) 😉 

Anyway, can we detect we are in such an area on the map? Or must we analyse a lot of segments around to make a guess if we are?

**Comment by berestovskyy** [comment]
I meant we might manually scan for the at grade connectors somewhere in US, for example. And deduct the appropriate length from the results (i.e. false positives).

I have my editor opened in Israel and voila here is an example of [a 71 m long AGC](https://www.waze.com/en-US/editor?env=il&lon=34.80062&lat=31.24066&s=71277847&zoom=5&segments=238393). It has a speed limit set, but I guess US guidelines allow to leave AGCs without speed limit set...

**Comment by berestovskyy** [comment]
I did not read the guidelines thoroughly ;) But people get frustrated when there are lots of unimportant reports, especially when reports contradict with people intentions or guidelines. So if we leave it as is, we will end up with more people completely filtered out those checks.

I guess the length is the way to go. Sure, we will cut some legit small segments, but there are custom checks to find and fix those.

We might remove or lower the length condition, once those large segments are done and people will be looking for some more work to do ;)
