### ISSUE TITLE
dev: compilation warning

### ISSUE THREAD

**Issue by berestovskyy** [WMEValidator/validator#77]
Dev branches in `validator` and in `i18n` repos are created. I missed the dev branch in i18n, but now it's fixed.

During compilation we have a warning:

    ./src/validate.js:3255: WARNING - Property getPoint never defined on ?
				var stopPoint = venue.$entryExitPoints[0].getPoint();

And the release version is crashing. David, I guess you forget to push the externs changes or I have missed them ;) Could you please have a look?

I tested GF version instead (without the advanced compilation) and it works fine. It reports a lot of issues with the parkings, so I guess we need an early feedback if some of those checks should be off for some countries.

Overall, I think it is a very good start for the alpha release.

**Comment by davidakachaos** [comment]
You haven't missed them 😉. I will try to fix this warning, but I didn't see a obvious way to add `getPoint` to the externals...

**Comment by davidakachaos** [comment]
Fixed in #78
