### ISSUE TITLE
Add lock check for Private Roads & Railways

### ISSUE THREAD

**Issue by jangliss** [WMEValidator/validator#90]
Currently there are checks for Freeway (150), Major(151)/Minor(152) highways, Ramps (153), and Primary Street (154). It's not uncommon for Private Roads & Railways to be locked at a different level as well.  While we can put this in a custom validation rule, it seems odd not to include it in the base (option 155 & 156 maybe?).

**Comment by berestovskyy** [comment]
Hey Jonathan,
Thanks for the suggestion. Do you plan to implement the change?

Andriy
